### ISSUE TITLE
cardioEM-4CH

### ISSUE THREAD

**Issue by whucsu** [MatteoSalvador/cardioEM-MAP#1]
thanks for sharing the project.
Is this project the same with "Real-time whole-heart electromechanical simulations using
Latent Neural Ordinary Differential Equations" , the mentioned linked "https://github.com/MatteoSalvador/cardioEM-4CH" can not be accessed.
thanks.

**Comment by MatteoSalvador** [comment]
This repository (`cardioEM-MAP`) refers to the publication at the following [link](https://www.sciencedirect.com/science/article/pii/S016926072300069X).
On the other hand, `cardioEM-4CH` will be made publicly available at the end of the peer-review process of this [arXiv  preprint](https://arxiv.org/abs/2306.05321).
The two works share similar methods for robust parameter estimation and inverse uncertainty quantification.
